version: 2.1

default_steps: &default_steps
  steps:
    - checkout
    - run: npm ci
    - run: ./run-snapshots.sh

jobs:
  openjdk_8_with_percy:
    # We've opted this OpenJDK version to be the one that runs and reports Percy's status
    docker:
      # OpenJDK 8. Node 10.
      - image: circleci/openjdk:8-node-browsers
    <<: *default_steps
  openjdk_11:
    docker:
      # OpenJDK 11. Node 10.
      - image: circleci/openjdk:11-node-browsers
    environment:
      PERCY_ENABLE: 0
    <<: *default_steps

workflows:
  version: 2
  test:
    jobs:
      - openjdk_8_with_percy
      - openjdk_11
